### ISSUE TITLE
Websocket fails to connect

### ISSUE THREAD

**Issue by SikFar** [bitfinexcom/bitfinex-api-py#42] opened 2019-12-21 10:51 UTC
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ X] performance
- [ ] feature request

#### Brief description
When trying to subscribe to the web-socket that gets the trade candles, the code occasionally crashes. Sometimes it failes to connect after 5 attempts, sometimes it manages to connect. More often than not it fails. Also this sometimes occur after running the code successfully for a short while. 

**Is the code somehow dependent on me be logged into the actual bitfinex website to connect the websocket?**
#### Steps to reproduce
- By running the subscribe_trades_candles.py example

##### Additional Notes:
```
[BfxWebsocket] [INFO] Websocket connected to wss://api-pub.bitfinex.com/ws/2
[BfxWebsocket] [INFO] {'event': 'info', 'version': 2, 'serverId': '412b8f9c-86a9-4c08-b5e9-beb797a79d3a', 'platform': {'status': 1}}
[BfxWebsocket] [INFO] Websocket opened.
[BfxSubscriptionManager] [INFO] Subscribing to channel candles
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f8220c577d0>
transport: <_SelectorSocketTransport fd=16 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 668, in _process_write_backlog
    data, offset = self._write_backlog[0]
IndexError: deque index out of range
Unexpected exception in keepalive ping task
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 984, in keepalive_ping
    ping_waiter = yield from self.ping()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 583, in ping
    yield from self.ensure_open()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
Error in data transfer
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/sslproto.py", line 668, in _process_write_backlog
    data, offset = self._write_backlog[0]
IndexError: deque index out of range
```

**Comment by JacobPlaster** [comment] 2019-12-25 11:39
Hey @SikFar, what version of python are you using? Python 3.7.1 had a lot of SSL fixes

**Comment by SikFar** [comment] 2019-12-25 12:47
Hi @JacobPlaster,
Its says 3.7

**Comment by gaieges** [comment] 2019-12-27 18:14
Got the same problem on `Python 3.7.5` and
```
bitfinex-api-py==1.1.2
asyncio==3.4.3
```

**Comment by gaieges** [comment] 2019-12-27 18:28
I can confirm that rolling back to 3.7.0 (and the remainder of libs the same) solves this issue.

**Comment by SikFar** [comment] 2019-12-28 09:01
Hi @gaieges , what do you mean by 

> (and the remainder of libs the same)

Rolling back to 3.7.0, did not seem to help me...

**Comment by gaieges** [comment] 2019-12-28 19:06
Meaning the versions of the other libs I pasted above were unchanged.

I should note that by "rolling back" I used a docker image `python:3.7.0-alpine`, vs using my brew-provided Python 3.7.5.

**Comment by gaieges** [comment] 2019-12-29 18:02
One other thing to try @SikFar  - try reverting to `bitfinex-api-py==1.1.2`

**Comment by JacobPlaster** [comment] 2020-01-02 15:58
Hi guys, PR opened to fix this issue here: https://github.com/bitfinexcom/bitfinex-api-py/pull/45

**Comment by JacobPlaster** [comment] 2020-01-09 11:41
#45 merged

Closing as Im now unable to reproduce this

**Closed by JacobPlaster** 2020-01-09 11:41 UTC
